/**
 * Battle Spirits card database for 26RSD01 赫焔ノ風牙 deck.
 * All effects are data-driven; no hardcoded logic.
 */

import type { CardDef } from './types.js';

const STARTER_DECK_IDS = [
  // Spirits: 11 cards
  'spirit_moon_shacco',
  'spirit_genie_bow',
  'spirit_ro_meek',
  'spirit_haria',
  'spirit_gun_gata',
  'spirit_cubel',
  'spirit_graipher',
  'spirit_seldalius',
  'spirit_lev_falus',
  'spirit_shinkoku_renshi',
  'spirit_hibutsu_akurai',

  // Nexuses: 2 cards
  'nexus_ukiyo_rock',
  'nexus_wind_fang_rock',

  // Magic: 3 cards
  'magic_break_claw',
  'magic_offering_draw',
  'magic_flame_hurricane',
];

export const CARD_DB: Record<string, CardDef> = {
  // === SPIRITS ===

  spirit_moon_shacco: {
    id: 'spirit_moon_shacco',
    name: 'ムーシャッコ',
    cardType: 'spirit',
    cost: 3,
    reductionCost: 1,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_moon_shacco.png',
    lv1: { cost: 1, bp: 2000 },
    lv2: { cost: 2, bp: 3000 },
    effects: [
      {
        trigger: 'battle_end',
        action: 'draw',
        value: 1,
        level: [2],
        condition: { maxHandSize: 5 },
        description: '[Lv2]「アタック中」バトル終了時、自分の手札が5枚以下なら、1枚ドローする',
      },
    ],
  },

  spirit_genie_bow: {
    id: 'spirit_genie_bow',
    name: 'ゲン=ボー',
    cardType: 'spirit',
    cost: 3,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['紅雲', '風牙'],
    exSymbol: true,
    skill: '真界放',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_genie_bow.png',
    lv1: { cost: 1, bp: 3000 },
    lv2: { cost: 3, bp: 5000 },
    effects: [
      {
        trigger: 'attack',
        action: 'boost_bp',
        value: 2000,
        duration: 'battle',
        level: [2],
        description: 'Lv2時、攻撃中にこのスピリットをBP+2000する',
      },
    ],
  },

  spirit_ro_meek: {
    id: 'spirit_ro_meek',
    name: 'ロワミーク',
    cardType: 'spirit',
    cost: 3,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['紅雲', '風牙'],
    exSymbol: true,
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_ro_meek.png',
    lv1: { cost: 1, bp: 3000 },
    lv2: { cost: 3, bp: 5000 },
    effects: [
      {
        trigger: 'summon',
        action: 'destroy_creature',
        target: 'opponent_creature',
        value: 3000,
        level: [1, 2],
        condition: { requiresFatiguedRed: true },
        description: '疲労状態の自分の赤のスピリットがいるなら、BP3000以下の相手のスピリット1体を破壊',
      },
    ],
  },

  spirit_haria: {
    id: 'spirit_haria',
    name: 'ハーリア',
    cardType: 'spirit',
    cost: 4,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_haria.png',
    lv1: { cost: 1, bp: 4000 },
    lv2: { cost: 3, bp: 6000 },
    effects: [
      {
        trigger: 'attack',
        action: 'search_deck',
        value: 2,
        count: 1,
        symbol: '風牙',
        level: [2],
        description: 'Lv2時、攻撃中にデッキの上から2枚をオープン。その中の系統：「風牙」を1枚手札に加え、残りは破棄',
      },
    ],
  },

  spirit_gun_gata: {
    id: 'spirit_gun_gata',
    name: 'ゲン＝ガタ',
    cardType: 'spirit',
    cost: 4,
    reductionCost: 3,
    symbolCount: 1,
    symbolColors: ['red'],
    exSymbol: true,
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_gun_gata.png',
    lv1: { cost: 1, bp: 5000 },
    lv2: { cost: 3, bp: 8000 },
  },

  spirit_cubel: {
    id: 'spirit_cubel',
    name: 'キュペル',
    cardType: 'spirit',
    cost: 5,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_cubel.png',
    lv1: { cost: 1, bp: 4000 },
    lv2: { cost: 4, bp: 7000 },
    effects: [
      {
        trigger: 'summon',
        action: 'place_core',
        value: 2,
        source: 'trash',
        level: [1, 2],
        condition: { excludeEXSymbol: true, excludeSoulCore: true },
        description: 'Lv1-2時、召喚時に自分のトラッシュのソウルコア以外のコア2個までをこのスピリットに置く',
      },
      {
        trigger: 'end_step',
        action: 'place_core',
        value: 20,
        source: 'trash',
        requiresTarget: true,
        level: [2],
        condition: { onlySoulCore: true, requiresSpirit: { lineage: '風牙' } },
        description: 'Lv2時、『自分のエンドステップ』系統：「風牙」を持つ自分のスピリット/ネクサス1つを指定できる。自分のトラッシュのソウルコアをそれに置く',
      },
    ],
  },

  spirit_graipher: {
    id: 'spirit_graipher',
    name: 'グライファー',
    cardType: 'spirit',
    cost: 5,
    reductionCost: 3,
    symbolCount: 1,
    symbolColors: ['red'],
    exSymbol: true,
    lineage: ['風牙'],
    skill: '真界放',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_graipher.png',
    lv1: { cost: 1, bp: 5000 },
    lv2: { cost: 3, bp: 7000, coreType: 'ソウルコア' },
    effects: [
      {
        trigger: 'attack',
        action: 'boost_bp',
        value: 3000,
        duration: 'battle',
        costAction: 'discard_hand',
        costSymbol: '風牙',
        isFlash: true,
        mode: 'flash',
        level: [1, 2],
        description: 'Lv1-2時、アタック中に【起動：フラッシュ】〔ターン1回〕自分の手札の系統：「風牙」を持つカード1枚を破棄する▶このバトル中、このスピリットをBP+3000する',
      },
      {
        trigger: 'attack',
        action: 'destroy_creature',
        target: 'opponent_creature',
        value: 3000,
        level: [2],
        description: 'Lv2時、攻撃時にBP3000以下の相手のスピリット1体を指定する。それを破壊する',
      },
    ],
  },

  spirit_seldalius: {
    id: 'spirit_seldalius',
    name: 'セルタリウス',
    cardType: 'spirit',
    cost: 6,
    reductionCost: 3,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    inheritance: true,
    skill: '継召',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_seldalius.png',
    lv1: { cost: 1, bp: 6000 },
    lv2: { cost: 2, bp: 7000 },
    effects: [
      {
        trigger: 'summon',
        action: 'trash_to_hand',
        symbol: '風牙',
        excludeId: 'spirit_seldalius',
        level: [1, 2],
        requiresTarget: true,
        condition: { excludeEXSymbol: true },
        description: 'Lv1-2時、召喚時に自分のトラッシュの「セルタリウス」以外の系統：「風牙」を持つスピリットカード1枚を指定する。それを手札に戻す',
      },
    ],
  },

  spirit_lev_falus: {
    id: 'spirit_lev_falus',
    name: '飛傑レウファルス',
    cardType: 'spirit',
    cost: 6,
    reductionCost: 3,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['紅雲', '風牙'],
    skill: '真界放',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_lev_falus.png',
    lv1: { cost: 1, bp: 6000 },
    lv2: { cost: 3, bp: 8000, coreType: 'ソウルコア' },
    effects: [
      {
        trigger: 'summon',
        action: 'destroy_creature',
        target: 'opponent_creature',
        value: 5000,
        level: [1, 2],
        condition: { requiresFatiguedRed: true },
        description: 'Lv1-2時、召喚時に疲労状態の系統：「風牙」を持つ自分のスピリットがいるなら、BP5000以下の相手のスピリット1体を破壊',
      },
      {
        trigger: 'attack',
        action: 'boost_bp',
        value: 2000,
        duration: 'battle',
        level: [2],
        description: 'Lv2時、攻撃中にこのスピリットをBP+2000する',
      },
    ],
  },

  spirit_shinkoku_renshi: {
    id: 'spirit_shinkoku_renshi',
    name: '飛赫レンシス',
    cardType: 'spirit',
    cost: 7,
    reductionCost: 4,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    inheritance: true,
    skill: '継召',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_shinkoku_renshi.png',
    lv1: { cost: 1, bp: 6000 },
    lv2: { cost: 3, bp: 8000 },
    effects: [
      {
        trigger: 'summon',
        action: 'destroy_creature',
        target: 'opponent_creature',
        value: 7000,
        level: [1, 2],
        requiresTarget: true,
        description: 'Lv1-2時、召喚時にBP7000以下の相手のスピリット1体を破壊',
      },
      {
        trigger: 'attack',
        action: 'place_core',
        value: 2,
        source: 'trash',
        requiresTarget: true,
        level: [2],
        condition: { excludeEXSymbol: true },
        description: 'Lv2時、アタック時に系統：「風牙」を持つ自分のスピリット1体を指定できる。自分のトラッシュのソウルコア以外のコア2個までをそれに置く',
      },
    ],
  },

  spirit_hibutsu_akurai: {
    id: 'spirit_hibutsu_akurai',
    name: '飛剛アクライ',
    cardType: 'spirit',
    cost: 7,
    reductionCost: 4,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    skill: '真界放',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/spirit_hibutsu_akurai.png',
    lv1: { cost: 1, bp: 7000 },
    lv2: { cost: 4, bp: 10000, coreType: 'ソウルコア' },
    effects: [
      {
        trigger: 'attack',
        action: 'boost_bp',
        value: 3000,
        duration: 'battle',
        costAction: 'discard_hand',
        costSymbol: '風牙',
        isFlash: true,
        mode: 'flash',
        level: [1, 2],
        description: 'Lv1-2時、アタック中に【起動：フラッシュ】〔ターン1回〕自分の手札の系統：「風牙」を持つカード1枚を破棄する▶このバトル中、このスピリットをBP+3000する',
      },
      {
        trigger: 'attack',
        action: 'search_deck',
        value: 3,
        count: 1,
        symbol: '風牙',
        level: [2],
        description: 'Lv2時、攻撃時にデッキの上から3枚をオープン。その中の系統：「風牙」を1枚手札に加え、残りは破棄',
      },
    ],
  },

  // === NEXUSES ===

  nexus_ukiyo_rock: {
    id: 'nexus_ukiyo_rock',
    name: '浮遊岩域',
    cardType: 'nexus',
    cost: 4,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/nexus_ukiyo_rock.png',
    lv1: { cost: 0, bp: 0 },
    lv2: { cost: 2, bp: 0 },
    effects: [
      {
        trigger: 'summon',
        action: 'trash_to_hand',
        symbol: '風牙',
        level: [1, 2],
        condition: { requiresFatiguedRed: true, maxCost: 4 },
        description: '疲労状態の自分の赤のスピリットがいるなら、自分のトラッシュのコスト4以下で系統：「風牙」を持つスピリットカード1枚を手札に戻す',
      },
      {
        trigger: 'attack',
        action: 'boost_bp',
        value: 2000,
        duration: 'battle',
        level: [2],
        multiTarget: true,
        condition: { requiresSkill: '継召' },
        description: 'Lv2時、自分のアタックステップに継召を持つ自分のスピリットすべてをBP+2000する',
      },
    ],
  },

  nexus_wind_fang_rock: {
    id: 'nexus_wind_fang_rock',
    name: '最奥：風牙岩',
    cardType: 'nexus',
    cost: 3,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    skill: '真界放',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/nexus_wind_fang_rock.png',
    lv1: { cost: 0, bp: 0 },
    lv2: { cost: 2, bp: 0, coreType: 'ソウルコア' },
    effects: [
      {
        trigger: 'attack',
        action: 'boost_bp',
        value: 2000,
        duration: 'battle',
        costExhaustSelf: true,
        isFlash: true,
        mode: 'flash',
        level: [1, 2],
        requiresTarget: true,
        targetType: 'attacking',
        description: '［Lv1-2］『自分のアタックステップ』【起動：フラッシュ】このネクサスを疲労させる▶アタックしている系統：「風牙」を持つ自分のスピリット1体を指定する。このバトル中、それをBP+2000する',
      },
      {
        trigger: 'destroy',
        action: 'place_core',
        value: 1,
        source: 'trash',
        level: [2],
        condition: { excludeEXSymbol: true, excludeSoulCore: true },
        description: 'Lv2時、自分が相手のスピリットを破壊した時、自分のスピリット1体を指定できる。自分のトラッシュのソウルコア以外のコア1個をそれに置く',
      },
    ],
  },

  // === MAGIC ===

  magic_break_claw: {
    id: 'magic_break_claw',
    name: 'ブレイククロー',
    cardType: 'magic',
    cost: 3,
    reductionCost: 2,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    exSymbol: true,
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/magic_break_claw.png',
    lv1: { cost: 0, bp: 0 },
    effects: [
      {
        trigger: 'immediate',
        action: 'destroy_nexus',
        requiresTarget: true,
        mode: 'main',
        condition: { excludeTargetSkill: '真界放' },
        description: 'メイン: 真界放していない相手のネクサス1つを指定する。それを破壊する',
      },
      {
        trigger: 'immediate',
        action: 'place_core',
        value: 1,
        source: 'trash',
        mode: 'main',
        condition: { requiresFatiguedRed: true, excludeSoulCore: true },
        description: 'その後、疲労状態の自分の赤のスピリットがいるなら、自分のトラッシュのソウルコア以外のコア1個をリザーブに置く',
      },
      {
        trigger: 'immediate',
        action: 'boost_bp',
        value: 3000,
        duration: 'turn',
        requiresTarget: true,
        mode: 'flash',
        description: 'フラッシュ: 自分のスピリット1体をこのターン中、BP+3000する',
      },
    ],
  },

  magic_offering_draw: {
    id: 'magic_offering_draw',
    name: 'オフェリングドロー',
    cardType: 'magic',
    cost: 4,
    reductionCost: 2,
    symbolCount: 0,
    symbolColors: ['red'],
    lineage: ['風牙'],
    inheritance: true,
    skill: '継召',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/magic_offering_draw.png',
    lv1: { cost: 0, bp: 0 },
    effects: [
      {
        trigger: 'immediate',
        action: 'search_deck',
        value: 3,
        count: 2,
        symbol: '風牙',
        mode: 'main',
        description: 'メイン: デッキの上から3枚をオープン。その中の系統：「風牙」を持つカード2枚を手札に加える。残りはデッキの下に戻す',
      },
      {
        trigger: 'immediate',
        action: 'boost_bp',
        value: 2000,
        duration: 'turn',
        requiresTarget: true,
        mode: 'flash',
        description: 'フラッシュ: 自分のスピリット1体をこのターン中、BP+2000する',
      },
    ],
  },

  magic_flame_hurricane: {
    id: 'magic_flame_hurricane',
    name: 'フレイムハリケーン',
    cardType: 'magic',
    cost: 6,
    reductionCost: 3,
    symbolCount: 1,
    symbolColors: ['red'],
    lineage: ['風牙'],
    exSymbol: true,
    skill: 'ソウルマジック：赤',
    cardSet: '26RSD01 バトスピエントリーデッキ 赫焔ノ風牙',
    imagePath: 'assets/cards/magic_flame_hurricane.png',
    lv1: { cost: 0, bp: 0, coreType: 'ソウルコア' },
    effects: [
      {
        trigger: 'immediate',
        action: 'destroy_creature',
        target: 'opponent_creature',
        value: 7000,
        mode: 'flash',
        requiresTarget: true,
        condition: { requiresSymbol: 'red' },
        description: 'フラッシュ: 場に赤シンボルがあり、ソウルコアを支払うことで使用可能。BP7000以下の相手のスピリット1体を指定する。それを破壊する。このターンに自分のライフが減っていたなら、かわりに指定するBPを10000以下にする',
      },
    ],
  },
};

export function getStarterDeck(): CardDef[] {
  return STARTER_DECK_IDS.map((id) => CARD_DB[id]!);
}
